apiVersion: v1
kind: Pod
metadata:
  name: tmpgo-httpserver
spec:
  # hostNetwork: true
  containers:
  - name: tmpgo-httpserver
    image: koitown/tmpgo:latest
    imagePullPolicy: Always
    command: ["/tmpgo"]
    ports:
    - containerPort: 10101
      hostPort: 10101
          
---
apiVersion: v1
kind: Service
metadata:
  name: tmpgo-httpserver
spec:
  selector:
    app: tmpgo-httpserver
  ports:
    - protocol: TCP
      name: http
      port: 10101
      targetPort: 10101
